// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebStore.Data;

namespace WebStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200315201809__initial")]
    partial class _initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WebStore.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acne",
                            Order = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Grune Erde",
                            Order = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Albiro",
                            Order = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ronhill",
                            Order = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Oddmolly",
                            Order = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Boudestijn",
                            Order = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rosch creative culture",
                            Order = 6
                        });
                });

            modelBuilder.Entity("WebStore.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            ImageUrl = "product1.jpg",
                            Name = "Белое платье",
                            Order = 0,
                            Price = 1025.0,
                            SectionId = 2
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            ImageUrl = "product2.jpg",
                            Name = "Розовое платье",
                            Order = 1,
                            Price = 1025.0,
                            SectionId = 2
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            ImageUrl = "product3.jpg",
                            Name = "Красное платье",
                            Order = 2,
                            Price = 1025.0,
                            SectionId = 2
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            ImageUrl = "product4.jpg",
                            Name = "Джинсы",
                            Order = 3,
                            Price = 1025.0,
                            SectionId = 2
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            ImageUrl = "product5.jpg",
                            Name = "Лёгкая майка",
                            Order = 4,
                            Price = 1025.0,
                            SectionId = 2
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            ImageUrl = "product6.jpg",
                            Name = "Лёгкое голубое поло",
                            Order = 5,
                            Price = 1025.0,
                            SectionId = 2
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            ImageUrl = "product7.jpg",
                            Name = "Платье белое",
                            Order = 6,
                            Price = 1025.0,
                            SectionId = 2
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            ImageUrl = "product8.jpg",
                            Name = "Костюм кролика",
                            Order = 7,
                            Price = 1025.0,
                            SectionId = 25
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 1,
                            ImageUrl = "product9.jpg",
                            Name = "Красное китайское платье",
                            Order = 8,
                            Price = 1025.0,
                            SectionId = 25
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            ImageUrl = "product10.jpg",
                            Name = "Женские джинсы",
                            Order = 9,
                            Price = 1025.0,
                            SectionId = 25
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            ImageUrl = "product11.jpg",
                            Name = "Джинсы женские",
                            Order = 10,
                            Price = 1025.0,
                            SectionId = 25
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            ImageUrl = "product12.jpg",
                            Name = "Летний костюм",
                            Order = 11,
                            Price = 1025.0,
                            SectionId = 25
                        });
                });

            modelBuilder.Entity("WebStore.Domain.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Спорт",
                            Order = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nike",
                            Order = 0,
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Under Armour",
                            Order = 1,
                            ParentId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adidas",
                            Order = 2,
                            ParentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Puma",
                            Order = 3,
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "ASICS",
                            Order = 4,
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Для мужчин",
                            Order = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fendi",
                            Order = 0,
                            ParentId = 7
                        },
                        new
                        {
                            Id = 9,
                            Name = "Guess",
                            Order = 1,
                            ParentId = 7
                        },
                        new
                        {
                            Id = 10,
                            Name = "Valentino",
                            Order = 2,
                            ParentId = 7
                        },
                        new
                        {
                            Id = 11,
                            Name = "Диор",
                            Order = 3,
                            ParentId = 7
                        },
                        new
                        {
                            Id = 12,
                            Name = "Версачи",
                            Order = 4,
                            ParentId = 7
                        },
                        new
                        {
                            Id = 13,
                            Name = "Армани",
                            Order = 5,
                            ParentId = 7
                        },
                        new
                        {
                            Id = 14,
                            Name = "Prada",
                            Order = 6,
                            ParentId = 7
                        },
                        new
                        {
                            Id = 15,
                            Name = "Дольче и Габбана",
                            Order = 7,
                            ParentId = 7
                        },
                        new
                        {
                            Id = 16,
                            Name = "Шанель",
                            Order = 8,
                            ParentId = 7
                        },
                        new
                        {
                            Id = 17,
                            Name = "Гуччи",
                            Order = 9,
                            ParentId = 7
                        },
                        new
                        {
                            Id = 18,
                            Name = "Для женщин",
                            Order = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "Fendi",
                            Order = 0,
                            ParentId = 18
                        },
                        new
                        {
                            Id = 20,
                            Name = "Guess",
                            Order = 1,
                            ParentId = 18
                        },
                        new
                        {
                            Id = 21,
                            Name = "Valentino",
                            Order = 2,
                            ParentId = 18
                        },
                        new
                        {
                            Id = 22,
                            Name = "Dior",
                            Order = 3,
                            ParentId = 18
                        },
                        new
                        {
                            Id = 23,
                            Name = "Versace",
                            Order = 4,
                            ParentId = 18
                        },
                        new
                        {
                            Id = 24,
                            Name = "Для детей",
                            Order = 3
                        },
                        new
                        {
                            Id = 25,
                            Name = "Мода",
                            Order = 4
                        },
                        new
                        {
                            Id = 26,
                            Name = "Для дома",
                            Order = 5
                        },
                        new
                        {
                            Id = 27,
                            Name = "Интерьер",
                            Order = 6
                        },
                        new
                        {
                            Id = 28,
                            Name = "Одежда",
                            Order = 7
                        },
                        new
                        {
                            Id = 29,
                            Name = "Сумки",
                            Order = 8
                        },
                        new
                        {
                            Id = 30,
                            Name = "Обувь",
                            Order = 9
                        });
                });

            modelBuilder.Entity("WebStore.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 54,
                            BirthDay = new DateTime(1966, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Амин",
                            Patronymic = "Ильясович",
                            SurName = "Суханов",
                            Telephone = "+7981-497-4244"
                        },
                        new
                        {
                            Id = 2,
                            Age = 62,
                            BirthDay = new DateTime(1958, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Иосиф",
                            Patronymic = "Бореславович",
                            SurName = "Лаврентьев",
                            Telephone = "+7993-076-4639"
                        },
                        new
                        {
                            Id = 3,
                            Age = 26,
                            BirthDay = new DateTime(1994, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Фердинанд",
                            Patronymic = "Никифорович",
                            SurName = "Зуев",
                            Telephone = "+7999-324-9965"
                        },
                        new
                        {
                            Id = 4,
                            Age = 47,
                            BirthDay = new DateTime(1973, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Конрад",
                            Patronymic = "Иакинфович",
                            SurName = "Лебедев",
                            Telephone = "+7982-387-0662"
                        },
                        new
                        {
                            Id = 5,
                            Age = 33,
                            BirthDay = new DateTime(1987, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Краснослав",
                            Patronymic = "Виленович",
                            SurName = "Зубов",
                            Telephone = "+7983-410-7908"
                        },
                        new
                        {
                            Id = 6,
                            Age = 47,
                            BirthDay = new DateTime(1973, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Амадей",
                            Patronymic = "Гастонович",
                            SurName = "Медведев",
                            Telephone = "+7985-412-2660"
                        },
                        new
                        {
                            Id = 7,
                            Age = 29,
                            BirthDay = new DateTime(1991, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Якун",
                            Patronymic = "Германович",
                            SurName = "Герасимов",
                            Telephone = "+7988-532-9900"
                        },
                        new
                        {
                            Id = 8,
                            Age = 47,
                            BirthDay = new DateTime(1973, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Зорий",
                            Patronymic = "Герасимович",
                            SurName = "Аксенов",
                            Telephone = "+7981-824-6986"
                        },
                        new
                        {
                            Id = 9,
                            Age = 72,
                            BirthDay = new DateTime(1948, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Шамиль",
                            Patronymic = "Эльдарович",
                            SurName = "Ильинский",
                            Telephone = "+7997-385-5799"
                        },
                        new
                        {
                            Id = 10,
                            Age = 41,
                            BirthDay = new DateTime(1979, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Граф",
                            Patronymic = "Мирославович",
                            SurName = "Моисеев",
                            Telephone = "+7982-912-0476"
                        },
                        new
                        {
                            Id = 11,
                            Age = 33,
                            BirthDay = new DateTime(1987, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Аарон",
                            Patronymic = "Агапович",
                            SurName = "Ильин",
                            Telephone = "+7984-274-5687"
                        },
                        new
                        {
                            Id = 12,
                            Age = 43,
                            BirthDay = new DateTime(1977, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Гоар",
                            Patronymic = "Гордейович",
                            SurName = "Гладков",
                            Telephone = "+7990-061-4358"
                        },
                        new
                        {
                            Id = 13,
                            Age = 52,
                            BirthDay = new DateTime(1968, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Гавриил",
                            Patronymic = "Радиславович",
                            SurName = "Власов",
                            Telephone = "+7993-956-0686"
                        },
                        new
                        {
                            Id = 14,
                            Age = 52,
                            BirthDay = new DateTime(1968, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Федот",
                            Patronymic = "Закирович",
                            SurName = "Галкин",
                            Telephone = "+7984-227-9481"
                        },
                        new
                        {
                            Id = 15,
                            Age = 69,
                            BirthDay = new DateTime(1951, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Хабиб",
                            Patronymic = "Камильович",
                            SurName = "Ильинский",
                            Telephone = "+7988-591-2003"
                        },
                        new
                        {
                            Id = 16,
                            Age = 45,
                            BirthDay = new DateTime(1975, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Бахрам",
                            Patronymic = "Вальтерович",
                            SurName = "Шевцов",
                            Telephone = "+7983-825-6306"
                        },
                        new
                        {
                            Id = 17,
                            Age = 60,
                            BirthDay = new DateTime(1960, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Лукий",
                            Patronymic = "Артамонович",
                            SurName = "Фадеев",
                            Telephone = "+7999-634-6473"
                        },
                        new
                        {
                            Id = 18,
                            Age = 70,
                            BirthDay = new DateTime(1950, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Анвар",
                            Patronymic = "Расимович",
                            SurName = "Борисов",
                            Telephone = "+7986-113-8659"
                        },
                        new
                        {
                            Id = 19,
                            Age = 48,
                            BirthDay = new DateTime(1972, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Архип",
                            Patronymic = "Лукьянович",
                            SurName = "Зеленин",
                            Telephone = "+7990-558-7521"
                        },
                        new
                        {
                            Id = 20,
                            Age = 69,
                            BirthDay = new DateTime(1951, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ильхам",
                            Patronymic = "Иосифович",
                            SurName = "Пастухов",
                            Telephone = "+7994-763-5951"
                        },
                        new
                        {
                            Id = 21,
                            Age = 67,
                            BirthDay = new DateTime(1953, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Родион",
                            Patronymic = "Арамович",
                            SurName = "Поликарпов",
                            Telephone = "+7996-431-2350"
                        },
                        new
                        {
                            Id = 22,
                            Age = 26,
                            BirthDay = new DateTime(1994, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Раис",
                            Patronymic = "Митяович",
                            SurName = "Малинин",
                            Telephone = "+7986-637-4561"
                        },
                        new
                        {
                            Id = 23,
                            Age = 63,
                            BirthDay = new DateTime(1957, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Вениамин",
                            Patronymic = "Рашидович",
                            SurName = "Михайлов",
                            Telephone = "+7987-370-2028"
                        },
                        new
                        {
                            Id = 24,
                            Age = 53,
                            BirthDay = new DateTime(1967, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Клементий",
                            Patronymic = "Дамирович",
                            SurName = "Мухин",
                            Telephone = "+7983-115-2208"
                        },
                        new
                        {
                            Id = 25,
                            Age = 39,
                            BirthDay = new DateTime(1981, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Иосиф",
                            Patronymic = "Ибрагимович",
                            SurName = "Плотников",
                            Telephone = "+7986-251-5141"
                        },
                        new
                        {
                            Id = 26,
                            Age = 52,
                            BirthDay = new DateTime(1968, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Густав",
                            Patronymic = "Антипович",
                            SurName = "Комаров",
                            Telephone = "+7999-655-4472"
                        },
                        new
                        {
                            Id = 27,
                            Age = 68,
                            BirthDay = new DateTime(1952, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Армен",
                            Patronymic = "Мирославович",
                            SurName = "Константинов",
                            Telephone = "+7998-068-8822"
                        },
                        new
                        {
                            Id = 28,
                            Age = 58,
                            BirthDay = new DateTime(1962, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Тамаз",
                            Patronymic = "Пименович",
                            SurName = "Поздняков",
                            Telephone = "+7987-324-8689"
                        },
                        new
                        {
                            Id = 29,
                            Age = 18,
                            BirthDay = new DateTime(2002, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ибрагим",
                            Patronymic = "Ремович",
                            SurName = "Сизов",
                            Telephone = "+7984-770-5237"
                        },
                        new
                        {
                            Id = 30,
                            Age = 43,
                            BirthDay = new DateTime(1977, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Леонард",
                            Patronymic = "Ольгердович",
                            SurName = "Горелов",
                            Telephone = "+7996-360-1094"
                        },
                        new
                        {
                            Id = 31,
                            Age = 39,
                            BirthDay = new DateTime(1981, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Родион",
                            Patronymic = "Гастонович",
                            SurName = "Третьяков",
                            Telephone = "+7990-696-4678"
                        },
                        new
                        {
                            Id = 32,
                            Age = 33,
                            BirthDay = new DateTime(1987, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Фанис",
                            Patronymic = "Рудольфович",
                            SurName = "Вешняков",
                            Telephone = "+7984-907-9991"
                        },
                        new
                        {
                            Id = 33,
                            Age = 24,
                            BirthDay = new DateTime(1996, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Армен",
                            Patronymic = "Муслимович",
                            SurName = "Хромов",
                            Telephone = "+7981-309-5955"
                        },
                        new
                        {
                            Id = 34,
                            Age = 33,
                            BirthDay = new DateTime(1987, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Адольф",
                            Patronymic = "Власийович",
                            SurName = "Новиков",
                            Telephone = "+7991-054-4512"
                        },
                        new
                        {
                            Id = 35,
                            Age = 25,
                            BirthDay = new DateTime(1995, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Рашид",
                            Patronymic = "Венедиктович",
                            SurName = "Вешняков",
                            Telephone = "+7985-442-0284"
                        },
                        new
                        {
                            Id = 36,
                            Age = 51,
                            BirthDay = new DateTime(1969, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Нифонт",
                            Patronymic = "Миленович",
                            SurName = "Демидов",
                            Telephone = "+7993-399-9672"
                        },
                        new
                        {
                            Id = 37,
                            Age = 18,
                            BirthDay = new DateTime(2002, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Рамиз",
                            Patronymic = "Власийович",
                            SurName = "Голиков",
                            Telephone = "+7992-079-6155"
                        },
                        new
                        {
                            Id = 38,
                            Age = 59,
                            BirthDay = new DateTime(1961, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Алан",
                            Patronymic = "Сильвестрович",
                            SurName = "Майоров",
                            Telephone = "+7986-726-6083"
                        },
                        new
                        {
                            Id = 39,
                            Age = 47,
                            BirthDay = new DateTime(1973, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Фердинанд",
                            Patronymic = "Иоаннович",
                            SurName = "Окулов",
                            Telephone = "+7991-831-6162"
                        },
                        new
                        {
                            Id = 40,
                            Age = 62,
                            BirthDay = new DateTime(1958, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Новомир",
                            Patronymic = "Митяович",
                            SurName = "Платонов",
                            Telephone = "+7985-602-8267"
                        },
                        new
                        {
                            Id = 41,
                            Age = 53,
                            BirthDay = new DateTime(1967, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Фарид",
                            Patronymic = "Светозарович",
                            SurName = "Беляев",
                            Telephone = "+7991-097-6698"
                        },
                        new
                        {
                            Id = 42,
                            Age = 40,
                            BirthDay = new DateTime(1980, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Рем",
                            Patronymic = "Маринович",
                            SurName = "Рябов",
                            Telephone = "+7999-806-7158"
                        },
                        new
                        {
                            Id = 43,
                            Age = 41,
                            BirthDay = new DateTime(1979, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Марин",
                            Patronymic = "Султанович",
                            SurName = "Тихонов",
                            Telephone = "+7992-643-3041"
                        },
                        new
                        {
                            Id = 44,
                            Age = 42,
                            BirthDay = new DateTime(1978, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Арий",
                            Patronymic = "Парфенийович",
                            SurName = "Пирогов",
                            Telephone = "+7980-882-9698"
                        },
                        new
                        {
                            Id = 45,
                            Age = 50,
                            BirthDay = new DateTime(1970, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Пимен",
                            Patronymic = "Равильович",
                            SurName = "Мухин",
                            Telephone = "+7995-296-6191"
                        },
                        new
                        {
                            Id = 46,
                            Age = 43,
                            BirthDay = new DateTime(1977, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Вениамин",
                            Patronymic = "Людвигович",
                            SurName = "Панков",
                            Telephone = "+7998-796-5223"
                        },
                        new
                        {
                            Id = 47,
                            Age = 53,
                            BirthDay = new DateTime(1967, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Рифат",
                            Patronymic = "Камильович",
                            SurName = "Краснов",
                            Telephone = "+7989-741-5656"
                        },
                        new
                        {
                            Id = 48,
                            Age = 41,
                            BirthDay = new DateTime(1979, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Остромир",
                            Patronymic = "Исайович",
                            SurName = "Мешков",
                            Telephone = "+7992-005-8391"
                        },
                        new
                        {
                            Id = 49,
                            Age = 60,
                            BirthDay = new DateTime(1960, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Орландо",
                            Patronymic = "Стефанович",
                            SurName = "Троицкий",
                            Telephone = "+7984-379-4018"
                        },
                        new
                        {
                            Id = 50,
                            Age = 67,
                            BirthDay = new DateTime(1953, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Тимон",
                            Patronymic = "Янович",
                            SurName = "Овчинников",
                            Telephone = "+7983-581-0111"
                        },
                        new
                        {
                            Id = 51,
                            Age = 55,
                            BirthDay = new DateTime(1965, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Арам",
                            Patronymic = "Мелентийович",
                            SurName = "Леонов",
                            Telephone = "+7983-509-1005"
                        },
                        new
                        {
                            Id = 52,
                            Age = 45,
                            BirthDay = new DateTime(1975, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Якун",
                            Patronymic = "Нифонтович",
                            SurName = "Старостин",
                            Telephone = "+7994-758-0490"
                        },
                        new
                        {
                            Id = 53,
                            Age = 20,
                            BirthDay = new DateTime(2000, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Рихард",
                            Patronymic = "Филимонович",
                            SurName = "Рожков",
                            Telephone = "+7981-636-1018"
                        },
                        new
                        {
                            Id = 54,
                            Age = 74,
                            BirthDay = new DateTime(1946, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Иннокентий",
                            Patronymic = "Вальтерович",
                            SurName = "Горелов",
                            Telephone = "+7988-252-7789"
                        },
                        new
                        {
                            Id = 55,
                            Age = 48,
                            BirthDay = new DateTime(1972, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Бернар",
                            Patronymic = "Джамалович",
                            SurName = "Третьяков",
                            Telephone = "+7994-032-8446"
                        },
                        new
                        {
                            Id = 56,
                            Age = 20,
                            BirthDay = new DateTime(2000, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Вилен",
                            Patronymic = "Исаакийович",
                            SurName = "Исаев",
                            Telephone = "+7998-399-8480"
                        },
                        new
                        {
                            Id = 57,
                            Age = 57,
                            BirthDay = new DateTime(1963, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Рамиз",
                            Patronymic = "Марович",
                            SurName = "Орлов",
                            Telephone = "+7989-455-1373"
                        },
                        new
                        {
                            Id = 58,
                            Age = 19,
                            BirthDay = new DateTime(2001, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Дементий",
                            Patronymic = "Евграфович",
                            SurName = "Уткин",
                            Telephone = "+7997-532-7215"
                        },
                        new
                        {
                            Id = 59,
                            Age = 29,
                            BirthDay = new DateTime(1991, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Рамиз",
                            Patronymic = "Конрадович",
                            SurName = "Волков",
                            Telephone = "+7981-143-7649"
                        },
                        new
                        {
                            Id = 60,
                            Age = 29,
                            BirthDay = new DateTime(1991, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Лукьян",
                            Patronymic = "Арменович",
                            SurName = "Корнилов",
                            Telephone = "+7986-481-6659"
                        },
                        new
                        {
                            Id = 61,
                            Age = 74,
                            BirthDay = new DateTime(1946, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Эдуард",
                            Patronymic = "Амвросийович",
                            SurName = "Аникин",
                            Telephone = "+7983-634-2581"
                        },
                        new
                        {
                            Id = 62,
                            Age = 36,
                            BirthDay = new DateTime(1984, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Платон",
                            Patronymic = "Наильович",
                            SurName = "Фадеев",
                            Telephone = "+7994-435-7711"
                        },
                        new
                        {
                            Id = 63,
                            Age = 50,
                            BirthDay = new DateTime(1970, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Велизар",
                            Patronymic = "Фаддейович",
                            SurName = "Панков",
                            Telephone = "+7996-438-9555"
                        },
                        new
                        {
                            Id = 64,
                            Age = 34,
                            BirthDay = new DateTime(1986, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Федосей",
                            Patronymic = "Амадейович",
                            SurName = "Безруков",
                            Telephone = "+7993-797-1041"
                        },
                        new
                        {
                            Id = 65,
                            Age = 73,
                            BirthDay = new DateTime(1947, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Архип",
                            Patronymic = "Зорийович",
                            SurName = "Мещеряков",
                            Telephone = "+7984-254-5228"
                        },
                        new
                        {
                            Id = 66,
                            Age = 28,
                            BirthDay = new DateTime(1992, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Макарий",
                            Patronymic = "Акакийович",
                            SurName = "Руднев",
                            Telephone = "+7986-688-2641"
                        },
                        new
                        {
                            Id = 67,
                            Age = 61,
                            BirthDay = new DateTime(1959, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ануфрий",
                            Patronymic = "Владиславович",
                            SurName = "Чернов",
                            Telephone = "+7982-235-0664"
                        },
                        new
                        {
                            Id = 68,
                            Age = 55,
                            BirthDay = new DateTime(1965, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Геласий",
                            Patronymic = "Левович",
                            SurName = "Степанов",
                            Telephone = "+7990-000-8899"
                        },
                        new
                        {
                            Id = 69,
                            Age = 54,
                            BirthDay = new DateTime(1966, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Валентин",
                            Patronymic = "Изяславович",
                            SurName = "Черняев",
                            Telephone = "+7987-364-0956"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
